In [78]:
#astype
#between
#clip
#drop_duplicates
#isnull
#dropna
#fillna
#isin
#copy

In [79]:
import numpy as np
import pandas as pd

In [80]:
subs = pd.read_csv('/content/subs.csv').iloc[:,0]
vk= pd.read_csv('/content/kohli_ipl.csv', index_col= 'match_no').iloc[:,0]
movie_series = pd.read_csv('/content/bollywood.csv', index_col= 'movie').iloc[:,0]

In [81]:
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [82]:
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [83]:
movie_series

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [84]:
#astype
import sys
sys.getsizeof(vk)

3472

In [85]:
sys.getsizeof(vk.astype('int32'))

2612

In [86]:
# between
vk[vk.between(50,100)]

match_no
15      50
34      58
41      71
44      56
45      67
52      70
57      57
68      73
71      51
73      58
74      65
80      57
81      93
82      99
85      56
97      67
99      73
103     51
104     62
110     82
116     75
117     79
119     80
120    100
122     52
127     75
129     54
131     54
132     62
134     64
137     55
141     58
144     57
145     92
148     68
152     70
160     84
162     67
164    100
175     72
178     90
182     50
188     72
197     51
198     53
209     58
213     73
Name: runs, dtype: int64

In [87]:
#clip
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [88]:
subs.clip(100,200)

0      100
1      100
2      100
3      100
4      100
      ...
360    200
361    200
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [89]:
temp = pd.Series([1,1,1,1,2,2,2,2,3,3,3,4])
temp

0     1
1     1
2     1
3     1
4     2
5     2
6     2
7     2
8     3
9     3
10    3
11    4
dtype: int64

In [90]:
temp.drop_duplicates()

0     1
4     2
8     3
11    4
dtype: int64

In [91]:
movie_series.drop_duplicates(keep ='last')

movie
Soni (film)               Geetika Vidya Ohlyan
Hum Chaar                          Prit Kamani
Mard Ko Dard Nahi Hota        Abhimanyu Dasani
Hamid (film)                Talha Arshad Reshi
Risknamaa                       Garima Agarwal
                                  ...
Hum Tumhare Hain Sanam          Shah Rukh Khan
Aankhen (2002 film)           Amitabh Bachchan
Saathiya (film)                   Vivek Oberoi
Company (film)                      Ajay Devgn
Awara Paagal Deewana              Akshay Kumar
Name: lead, Length: 566, dtype: object

In [92]:
temp.duplicated().sum()

np.int64(8)

In [93]:
vk.duplicated().sum()

np.int64(137)

In [94]:
movie_series.drop_duplicates()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Sssshhh...                              Tanishaa Mukerji
Rules: Pyaar Ka Superhit Formula                  Tanuja
Right Here Right Now (film)                        Ankit
Talaash: The Hunt Begins...                Rakhee Gulzar
The Pink Mirror                          Edwin Fernandes
Name: lead, Length: 566, dtype: object

In [95]:
temp = pd.Series([1,2,3,np.nan,5,6,np.nan,8])
temp

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
5    6.0
6    NaN
7    8.0
dtype: float64

In [96]:
temp.size

8

In [97]:
temp.count()

np.int64(6)

In [98]:
#isnull
vk.isnull()

match_no
1      False
2      False
3      False
4      False
5      False
       ...
211    False
212    False
213    False
214    False
215    False
Name: runs, Length: 215, dtype: bool

In [99]:
vk.isnull().sum()

np.int64(0)

In [100]:
temp.isnull().sum()

np.int64(2)

In [101]:
temp.dropna()

0    1.0
1    2.0
2    3.0
4    5.0
5    6.0
7    8.0
dtype: float64

In [102]:
temp.fillna(8)

0    1.0
1    2.0
2    3.0
3    8.0
4    5.0
5    6.0
6    8.0
7    8.0
dtype: float64

In [103]:
vk[(vk == 49) | (vk == 99 )] # one alternative method for isin

match_no
82    99
86    49
Name: runs, dtype: int64

In [104]:
#isin
vk[vk.isin([49,99])]

match_no
82    99
86    49
Name: runs, dtype: int64

In [105]:
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [106]:
new = vk.head().copy()

In [107]:
new

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [108]:
new[1] = 100

In [109]:
new

match_no
1    100
2     23
3     13
4     12
5      1
Name: runs, dtype: int64

In [110]:
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64